AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for ParticipantApi

Globals:
  Function:
    Timeout: 10

Resources:
  ParticipantApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/ParticipantApi/
      Handler: ParticipantApi::ParticipantApi.Function::FunctionHandlerAsync
      Runtime: dotnetcore3.1
      Role: arn:aws:iam::536374685097:role/nihr-dte-dev-eu-west-2-lambdaRole
      MemorySize: 256
      Environment:
        Variables:
          ASPNETCORE_ENVIRONMENT: PassInFromRunConfiguration
          Cpms__UserName: PassInFromRunConfiguration
          Cpms__Password: PassInFromRunConfiguration
          AWS_SECRET_MANAGER_SECRET_NAME: PassInFromRunConfiguration
      Events:
        GetAllStudies:
          Type: Api
          Properties:
            Path: /api/study
            Method: get
        GetStudyById:
          Type: Api
          Properties:
            Path: /api/study/{id}
            Method: get
        PostStudy:
          Type: Api
          Properties:
            Path: /api/study
            Method: post
        PutStudy:
          Type: Api
          Properties:
            Path: /api/study/{id}
            Method: put
        DeleteStudy:
          Type: Api
          Properties:
            Path: /api/study/{id}
            Method: delete

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ParticipantApiApi:
    Description: "API Gateway endpoint URL for Prod stage for ParticipantApi function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ParticipantApiFunction:
    Description: "ParticipantApi Lambda Function ARN"
    Value: !GetAtt ParticipantApiFunction.Arn
#  ParticipantApiFunctionIamRole:
#    Description: "Implicit IAM Role created for ParticipantApi function"
#    Value: !GetAtt ParticipantApiFunctionRole.Arn
